name: APTAT
favicon: null
layout_spectrum: 0.023053016513586044
typography_spectrum: 0.302572010550648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8046081915963441
  lightness: 0.46610674797557294
  saturation: 0.17774097993969917
  rhythmicContrast: 0.8702069981954992
purpose: []
