name: APTAT
favicon: null
layout_spectrum: 0.58059
typography_spectrum: 0.302572010550648
title: APTAT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b91f25'
    - '#000000'
    - '#ffffff'
    - '#888888'
    - '#2e6789'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
